services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sinso\AppRoutes\:
    resource: '../Classes/*'

  lowlevel.configuration.module.provider.app_routes:
    class: 'Sinso\AppRoutes\ConfigurationModuleProvider\AppRoutesProvider'
    tags:
      - name: 'lowlevel.configuration.module.provider'
        identifier: 'appRoutesConfiguration'
        label: 'App Routes'
